import localFont from "next/font/local";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Poligon",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
  <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} relative antialiased h-full @container mx-auto`}
        >
          <div className="absolute z--1 min-h-fit h-full w-full overflow-hidden">
            <div className="stars"></div>
            <div className="stars2"></div>
            <div className="stars3"></div>
          </div>
          <Navbar />
          {children}
        </body>
      </html>
  </ClerkProvider>
  );
}
