import localFont from "next/font/local";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Poligon",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
  <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
        >
          <div className="stars z--10"></div>
          <div className="stars2 z--10"></div>
          <div className="stars3 z--10"></div>
          <Navbar />
          {children}
        </body>
      </html>
  </ClerkProvider>
  );
}
